# @package _global_
defaults:
  - override /model: yolox

model:
  backbone:
    name: CSPDarknet
    input_channels: 3
    out_features: [dark3, dark4, dark5]
    depth: 0.33
    width: 0.5 
    depthwise: False
    act: "silu"
    in_res_hw:
      - ???
      - ???


  fpn:
    name: PAFPN
    compile:
      enable: False
      args:
        mode: reduce-overhead
    depth: 0.33 # round(depth * 3) == num bottleneck blocks
    # stage 1 is the first and len(num_layers) is the last
    in_stages: [dark3, dark4, dark5]
    depthwise: False
    act: "silu"
  head:
    name: YoloX
    compile:
      enable: False
      args:
        mode: reduce-overhead
    depthwise: False
    act: "silu"
  postprocess:
    confidence_threshold: 0.1
    nms_threshold: 0.45
